/*
 * Copyright (C) 2026 ChromaWay AB. See LICENSE for license information.
 */

package com.chromia.rellplayground.teavm;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.teavm.model.AccessLevel;
import org.teavm.model.ClassHolder;
import org.teavm.model.ClassHolderTransformer;
import org.teavm.model.ClassHolderTransformerContext;
import org.teavm.model.ElementModifier;
import org.teavm.model.FieldHolder;
import org.teavm.model.MethodDescriptor;
import org.teavm.model.MethodHolder;
import org.teavm.model.ValueType;
import org.teavm.model.emit.ProgramEmitter;

/**
 * Walks each class TeaVM loads; for the ones listed in [MISSING_METHODS] (TeaVM-classlib
 * core classes the bridge's transitive deps reference reflectively), adds a single throw-
 * UnsupportedOperationException stub for every signature TeaVM otherwise reports as
 * "Method X was not found".
 *
 * Entries are keyed by the *final* (TeaVM-renamed) class name and store a list of methods
 * as `<name>(<descriptor>)`. Descriptors follow JVMS section 4.3.3:
 *
 *     "(I)Z"               static boolean foo(int)
 *     "(Ljava/lang/Class;)Ljava/lang/Module;"
 *     "()V"                no args, void
 *
 * If a class isn't on the bridge's classpath we silently skip it — no harm done.
 */
final class MissingMethodInjector implements ClassHolderTransformer {

    /**
     * Methods to graft onto TeaVM-emulated classes. Each entry is `methodName(descriptor)`.
     * Some descriptors reference classes that aren't in TeaVM's classlib (e.g.
     * `java.lang.Module`, `java.lang.invoke.VarHandle`); those classes live as empty stubs
     * in the teavm-stubs JAR generated by `:bridge:generateTeavmStubs`, so the references
     * resolve.
     */
    private static final Map<String, List<String>> MISSING_METHODS = new HashMap<>();

    /**
     * Field references the dep analyser flagged. Each entry is `name|descriptor[|static]`.
     * Examples:
     *   "value|Ljava/math/BigInteger;"               instance field of type BigInteger
     *   "NULLABLE|Lio/r2dbc/spi/Nullability;|static" static enum constant
     */
    private static final Map<String, List<String>> MISSING_FIELDS = new HashMap<>();

    /**
     * Methods to stub with a body that returns the receiver (`return this`). Only meaningful
     * for instance methods whose return type is assignable from the declaring class — used
     * specifically for `Class.arrayType()`.
     */
    private static final java.util.Set<String> RETURN_THIS_METHODS = new java.util.HashSet<>();

    private static void addReturnThisMethods(String className, List<String> methods) {
        for (var m : methods) RETURN_THIS_METHODS.add(className + "#" + m);
    }

    /**
     * Methods that already exist on the class but whose body should be REPLACED with a silent
     * return-default stub for the TeaVM build only. Used to short-circuit JVM-only code paths
     * (e.g. `Class.getResource` + `Properties.load`) whose bytecode references would otherwise
     * drag the JVM-only classes into TeaVM reachability analysis.
     *
     * The method is expected to EXIST already — the program is overwritten in place rather
     * than added. JVM behavior in upstream rell3 is preserved.
     */
    private static final java.util.Set<String> REPLACE_BODY_METHODS = new java.util.HashSet<>();

    private static void addReplaceBodyMethods(String className, List<String> methods) {
        for (var m : methods) REPLACE_BODY_METHODS.add(className + "#" + m);
    }

    /**
     * Merges entries into [MISSING_METHODS]. Prior calls with the same `className` are not
     * overwritten — the new method names are appended. Makes it safe to grow the list in
     * incremental "discovered another round of missing methods" patches without manually
     * keeping each class's full list in one place.
     */
    private static void addMethods(String className, List<String> methods) {
        MISSING_METHODS.merge(className, methods, (a, b) -> {
            var combined = new java.util.ArrayList<String>(a.size() + b.size());
            combined.addAll(a);
            combined.addAll(b);
            return combined;
        });
    }

    private static void addFields(String className, List<String> fields) {
        MISSING_FIELDS.merge(className, fields, (a, b) -> {
            var combined = new java.util.ArrayList<String>(a.size() + b.size());
            combined.addAll(a);
            combined.addAll(b);
            return combined;
        });
    }

    static {
        // java.lang.Class — JDK 17+ reflective additions not in TeaVM-classlib's TClass.
        addMethods("java.lang.Class", List.of(
                "arrayType()Ljava/lang/Class;",
                "getEnclosingConstructor()Ljava/lang/reflect/Constructor;",
                "getEnclosingMethod()Ljava/lang/reflect/Method;",
                "getGenericInterfaces()[Ljava/lang/reflect/Type;",
                "getGenericSuperclass()Ljava/lang/reflect/Type;",
                "getPackageName()Ljava/lang/String;",
                "getRecordComponents()[Ljava/lang/reflect/RecordComponent;",
                "getResource(Ljava/lang/String;)Ljava/net/URL;",
                "isAnonymousClass()Z",
                "isRecord()Z"
        ));
        addMethods("java.lang.ClassLoader", List.of(
                "getResource(Ljava/lang/String;)Ljava/net/URL;",
                "loadClass(Ljava/lang/String;)Ljava/lang/Class;"
        ));
        addMethods("java.lang.Long", List.of(
                "parseUnsignedLong(Ljava/lang/String;I)J"
        ));
        addMethods("java.lang.String", List.of(
                "<init>([BIII)V"
        ));
        addMethods("java.lang.reflect.Constructor", List.of(
                "getParameters()[Ljava/lang/reflect/Parameter;"
        ));
        addMethods("java.lang.reflect.Field", List.of(
                "getBoolean(Ljava/lang/Object;)Z",
                "getByte(Ljava/lang/Object;)B",
                "getChar(Ljava/lang/Object;)C",
                "getDouble(Ljava/lang/Object;)D",
                "getFloat(Ljava/lang/Object;)F",
                "getInt(Ljava/lang/Object;)I",
                "getLong(Ljava/lang/Object;)J",
                "getShort(Ljava/lang/Object;)S",
                "setBoolean(Ljava/lang/Object;Z)V",
                "setByte(Ljava/lang/Object;B)V",
                "setChar(Ljava/lang/Object;C)V",
                "setDouble(Ljava/lang/Object;D)V",
                "setFloat(Ljava/lang/Object;F)V",
                "setInt(Ljava/lang/Object;I)V",
                "setLong(Ljava/lang/Object;J)V",
                "setShort(Ljava/lang/Object;S)V"
        ));
        addMethods("java.lang.reflect.Method", List.of(
                "getDefaultValue()Ljava/lang/Object;"
        ));
        addMethods("java.util.Calendar", List.of(
                "getDisplayNames(IILjava/util/Locale;)Ljava/util/Map;",
                "getWeekYear()I"
        ));
        addMethods("java.util.TimeZone", List.of(
                "observesDaylightTime()Z"
        ));
        addMethods("java.util.UUID", List.of(
                "<init>(JJ)V",
                "getLeastSignificantBits()J",
                "getMostSignificantBits()J"
        ));
        addMethods("java.util.regex.Matcher", List.of(
                "replaceAll(Ljava/util/function/Function;)Ljava/lang/String;"
        ));

        // ====================================================================================
        // Second wave — methods discovered after the T-prefix stub renamer started working,
        // i.e. once jOOQ / jackson / kotlin-reflect actually started seeing the empty stub
        // classes the bridge ships. Same throw-UOE treatment; same "never actually called at
        // runtime" rationale.
        // ====================================================================================
        addMethods("java.beans.ConstructorProperties", List.of(
                "value()[Ljava/lang/String;"
        ));
        addMethods("java.lang.reflect.GenericArrayType", List.of(
                "getGenericComponentType()Ljava/lang/reflect/Type;"
        ));
        addMethods("java.lang.reflect.ParameterizedType", List.of(
                "getActualTypeArguments()[Ljava/lang/reflect/Type;",
                "getOwnerType()Ljava/lang/reflect/Type;",
                "getRawType()Ljava/lang/reflect/Type;"
        ));
        addMethods("java.lang.reflect.Proxy", List.of(
                "newProxyInstance(Ljava/lang/ClassLoader;[Ljava/lang/Class;Ljava/lang/reflect/InvocationHandler;)Ljava/lang/Object;"
        ));
        addMethods("java.lang.reflect.TypeVariable", List.of(
                "getBounds()[Ljava/lang/reflect/Type;",
                "getGenericDeclaration()Ljava/lang/reflect/GenericDeclaration;",
                "getName()Ljava/lang/String;"
        ));
        addMethods("java.lang.reflect.WildcardType", List.of(
                "getLowerBounds()[Ljava/lang/reflect/Type;",
                "getUpperBounds()[Ljava/lang/reflect/Type;"
        ));
        addMethods("java.net.InetAddress", List.of(
                "getByName(Ljava/lang/String;)Ljava/net/InetAddress;",
                "getHostAddress()Ljava/lang/String;"
        ));
        addMethods("java.net.InetSocketAddress", List.of(
                "getAddress()Ljava/net/InetAddress;",
                "getHostName()Ljava/lang/String;",
                "getPort()I"
        ));
        addMethods("java.security.MessageDigest", List.of(
                "<init>(Ljava/lang/String;)V",
                "digest([B)[B",
                "getInstance(Ljava/lang/String;)Ljava/security/MessageDigest;"
        ));
        addMethods("java.security.Security", List.of(
                "getProperty(Ljava/lang/String;)Ljava/lang/String;"
        ));
        addMethods("java.sql.Array", List.of(
                "free()V",
                "getArray()Ljava/lang/Object;",
                "getResultSet()Ljava/sql/ResultSet;"
        ));
        addMethods("java.sql.Blob", List.of(
                "length()J"
        ));
        addMethods("java.sql.Connection", List.of(
                "close()V",
                "getAutoCommit()Z",
                "getMetaData()Ljava/sql/DatabaseMetaData;",
                "getSchema()Ljava/lang/String;",
                "prepareStatement(Ljava/lang/String;)Ljava/sql/PreparedStatement;",
                "prepareStatement(Ljava/lang/String;I)Ljava/sql/PreparedStatement;",
                "prepareStatement(Ljava/lang/String;II)Ljava/sql/PreparedStatement;",
                "prepareStatement(Ljava/lang/String;III)Ljava/sql/PreparedStatement;",
                "prepareStatement(Ljava/lang/String;[Ljava/lang/String;)Ljava/sql/PreparedStatement;",
                "releaseSavepoint(Ljava/sql/Savepoint;)V",
                "rollback(Ljava/sql/Savepoint;)V",
                "setAutoCommit(Z)V",
                "setSavepoint(Ljava/lang/String;)Ljava/sql/Savepoint;"
        ));
        addMethods("java.sql.DatabaseMetaData", List.of(
                "getCatalogs()Ljava/sql/ResultSet;",
                "getColumns(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;",
                "getConnection()Ljava/sql/Connection;",
                "getImportedKeys(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;",
                "getIndexInfo(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)Ljava/sql/ResultSet;",
                "getPrimaryKeys(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;",
                "getSchemas()Ljava/sql/ResultSet;",
                "getTables(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/sql/ResultSet;"
        ));
        addMethods("java.sql.Date", List.of(
                "<init>(J)V",
                "getTime()J",
                "getYear()I",
                "toLocalDate()Ljava/time/LocalDate;",
                "valueOf(Ljava/lang/String;)Ljava/sql/Date;",
                "valueOf(Ljava/time/LocalDate;)Ljava/sql/Date;"
        ));
        addMethods("java.sql.DriverManager", List.of(
                "getConnection(Ljava/lang/String;)Ljava/sql/Connection;",
                "getConnection(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/Connection;"
        ));
        addMethods("java.sql.PreparedStatement", List.of(
                "close()V",
                "execute()Z",
                "executeQuery()Ljava/sql/ResultSet;",
                "executeUpdate()I",
                "getConnection()Ljava/sql/Connection;",
                "getGeneratedKeys()Ljava/sql/ResultSet;",
                "getMoreResults()Z",
                "getMoreResults(I)Z",
                "getResultSet()Ljava/sql/ResultSet;",
                "getUpdateCount()I",
                "getWarnings()Ljava/sql/SQLWarning;",
                "setArray(ILjava/sql/Array;)V",
                "setBigDecimal(ILjava/math/BigDecimal;)V",
                "setBlob(ILjava/sql/Blob;)V",
                "setBoolean(IZ)V",
                "setByte(IB)V",
                "setBytes(I[B)V",
                "setClob(ILjava/sql/Clob;)V",
                "setDate(ILjava/sql/Date;)V",
                "setDouble(ID)V",
                "setFetchSize(I)V",
                "setFloat(IF)V",
                "setInt(II)V",
                "setLong(IJ)V",
                "setMaxRows(I)V",
                "setNString(ILjava/lang/String;)V",
                "setNull(II)V",
                "setObject(ILjava/lang/Object;)V",
                "setPoolable(Z)V",
                "setQueryTimeout(I)V",
                "setShort(IS)V",
                "setString(ILjava/lang/String;)V",
                "setTime(ILjava/sql/Time;)V",
                "setTimestamp(ILjava/sql/Timestamp;)V",
                "unwrap(Ljava/lang/Class;)Ljava/lang/Object;"
        ));
        addMethods("java.sql.ResultSet", List.of(
                "close()V",
                "getArray(I)Ljava/sql/Array;",
                "getBigDecimal(I)Ljava/math/BigDecimal;",
                "getBlob(I)Ljava/sql/Blob;",
                "getBoolean(I)Z",
                "getByte(I)B",
                "getBytes(I)[B",
                "getClob(I)Ljava/sql/Clob;",
                "getDate(I)Ljava/sql/Date;",
                "getDouble(I)D",
                "getFloat(I)F",
                "getInt(I)I",
                "getLong(I)J",
                "getMetaData()Ljava/sql/ResultSetMetaData;",
                "getNString(I)Ljava/lang/String;",
                "getObject(I)Ljava/lang/Object;",
                "getObject(ILjava/lang/Class;)Ljava/lang/Object;",
                "getObject(ILjava/util/Map;)Ljava/lang/Object;",
                "getShort(I)S",
                "getString(I)Ljava/lang/String;",
                "getTime(I)Ljava/sql/Time;",
                "getTimestamp(I)Ljava/sql/Timestamp;",
                "next()Z",
                "wasNull()Z"
        ));
        addMethods("java.sql.ResultSetMetaData", List.of(
                "getColumnCount()I",
                "getColumnLabel(I)Ljava/lang/String;",
                "getPrecision(I)I",
                "getSchemaName(I)Ljava/lang/String;"
        ));
        addMethods("java.sql.SQLException", List.of(
                "<init>(Ljava/lang/String;Ljava/lang/String;ILjava/lang/Throwable;)V",
                "<init>(Ljava/lang/String;Ljava/lang/Throwable;)V",
                "getErrorCode()I",
                "getMessage()Ljava/lang/String;",
                "getSQLState()Ljava/lang/String;",
                "setNextException(Ljava/sql/SQLException;)V"
        ));
        addMethods("java.sql.SQLWarning", List.of(
                "<init>(Ljava/lang/String;)V",
                "<init>(Ljava/lang/String;Ljava/lang/Throwable;)V"
        ));
        addMethods("java.sql.Statement", List.of(
                "close()V"
        ));
        addMethods("java.sql.Struct", List.of(
                "getAttributes()[Ljava/lang/Object;"
        ));
        addMethods("java.sql.Time", List.of(
                "<init>(J)V",
                "toLocalTime()Ljava/time/LocalTime;",
                "valueOf(Ljava/lang/String;)Ljava/sql/Time;",
                "valueOf(Ljava/time/LocalTime;)Ljava/sql/Time;"
        ));
        addMethods("java.sql.Timestamp", List.of(
                "<init>(J)V",
                "getTime()J",
                "toLocalDateTime()Ljava/time/LocalDateTime;",
                "valueOf(Ljava/lang/String;)Ljava/sql/Timestamp;",
                "valueOf(Ljava/time/LocalDateTime;)Ljava/sql/Timestamp;"
        ));
        addMethods("java.sql.Wrapper", List.of(
                "isWrapperFor(Ljava/lang/Class;)Z"
        ));
        addMethods("java.util.Scanner", List.of(
                "<init>(Ljava/lang/Readable;)V",
                "next()Ljava/lang/String;"
        ));
        addMethods("java.util.concurrent.atomic.AtomicLongArray", List.of(
                "<init>(I)V",
                "get(I)J"
        ));
        addMethods("java.util.concurrent.atomic.AtomicReferenceArray", List.of(
                "<init>(I)V",
                "get(I)Ljava/lang/Object;",
                "getAndSet(ILjava/lang/Object;)Ljava/lang/Object;",
                "set(ILjava/lang/Object;)V"
        ));
        addMethods("java.util.concurrent.locks.Lock", List.of(
                "lock()V",
                "tryLock()Z",
                "tryLock(JLjava/util/concurrent/TimeUnit;)Z",
                "unlock()V"
        ));
        addMethods("java.util.concurrent.locks.ReentrantLock", List.of(
                "lock()V",
                "tryLock()Z",
                "unlock()V"
        ));
        addMethods("javax.xml.namespace.QName", List.of(
                "<init>(Ljava/lang/String;Ljava/lang/String;)V"
        ));
        addMethods("javax.xml.parsers.DocumentBuilder", List.of(
                "parse(Lorg/xml/sax/InputSource;)Lorg/w3c/dom/Document;"
        ));
        addMethods("javax.xml.parsers.DocumentBuilderFactory", List.of(
                "newInstance()Ljavax/xml/parsers/DocumentBuilderFactory;",
                "setExpandEntityReferences(Z)V",
                "setFeature(Ljava/lang/String;Z)V",
                "setSchema(Ljavax/xml/validation/Schema;)V",
                "setXIncludeAware(Z)V"
        ));
        addMethods("javax.xml.parsers.SAXParserFactory", List.of(
                "newInstance()Ljavax/xml/parsers/SAXParserFactory;",
                "setFeature(Ljava/lang/String;Z)V"
        ));

        // ====================================================================================
        // Third wave — methods that surfaced after the second-wave method stubs unlocked the
        // jOOQ/jaxb/jackson static-init paths. These are all on the existing stub classes;
        // `addMethods` appends rather than overwrites.
        // ====================================================================================
        addMethods("java.lang.ThreadGroup", List.of(
                "<init>(Ljava/lang/String;)V"
        ));
        addMethods("java.lang.reflect.Parameter", List.of(
                "getName()Ljava/lang/String;"
        ));
        addMethods("java.lang.reflect.RecordComponent", List.of(
                "getName()Ljava/lang/String;",
                "getType()Ljava/lang/Class;"
        ));
        addMethods("java.sql.Blob", List.of(
                "free()V",
                "getBytes(JI)[B"
        ));
        addMethods("java.sql.Clob", List.of(
                "free()V",
                "length()J"
        ));
        addMethods("java.sql.Connection", List.of(
                "createBlob()Ljava/sql/Blob;",
                "createStatement()Ljava/sql/Statement;",
                "createStatement(II)Ljava/sql/Statement;",
                "createStatement(III)Ljava/sql/Statement;"
        ));
        addMethods("java.sql.DatabaseMetaData", List.of(
                "getDatabaseMajorVersion()I"
        ));
        addMethods("java.sql.Date", List.of(
                "getMonth()I"
        ));
        addMethods("java.sql.ResultSet", List.of(
                "absolute(I)Z",
                "getType()I",
                "isClosed()Z"
        ));
        addMethods("java.sql.ResultSetMetaData", List.of(
                "getColumnName(I)Ljava/lang/String;",
                "getScale(I)I",
                "getTableName(I)Ljava/lang/String;",
                "isNullable(I)I"
        ));
        addMethods("java.sql.SQLException", List.of(
                "<init>(Ljava/lang/String;)V",
                "getCause()Ljava/lang/Throwable;"
        ));
        addMethods("java.sql.Statement", List.of(
                "execute(Ljava/lang/String;)Z",
                "execute(Ljava/lang/String;I)Z",
                "execute(Ljava/lang/String;[I)Z",
                "execute(Ljava/lang/String;[Ljava/lang/String;)Z",
                "executeQuery(Ljava/lang/String;)Ljava/sql/ResultSet;",
                "executeUpdate(Ljava/lang/String;)I",
                "executeUpdate(Ljava/lang/String;I)I",
                "executeUpdate(Ljava/lang/String;[I)I",
                "executeUpdate(Ljava/lang/String;[Ljava/lang/String;)I",
                "getConnection()Ljava/sql/Connection;",
                "getGeneratedKeys()Ljava/sql/ResultSet;",
                "getMoreResults()Z",
                "getMoreResults(I)Z",
                "getResultSet()Ljava/sql/ResultSet;",
                "getUpdateCount()I",
                "getWarnings()Ljava/sql/SQLWarning;",
                "setFetchSize(I)V",
                "setMaxRows(I)V",
                "setPoolable(Z)V",
                "setQueryTimeout(I)V",
                "unwrap(Ljava/lang/Class;)Ljava/lang/Object;"
        ));
        addMethods("java.sql.Time", List.of(
                "getTime()J"
        ));
        addMethods("java.sql.Timestamp", List.of(
                "getNanos()I",
                "setNanos(I)V"
        ));
        addMethods("java.util.Locale$Builder", List.of(
                "build()Ljava/util/Locale;",
                "setExtension(CLjava/lang/String;)Ljava/util/Locale$Builder;",
                "setLanguage(Ljava/lang/String;)Ljava/util/Locale$Builder;"
        ));
        addMethods("java.util.Scanner", List.of(
                "useDelimiter(Ljava/lang/String;)Ljava/util/Scanner;"
        ));
        addMethods("java.util.concurrent.atomic.AtomicLongArray", List.of(
                "lazySet(IJ)V"
        ));
        addMethods("java.util.concurrent.atomic.AtomicReferenceArray", List.of(
                "lazySet(ILjava/lang/Object;)V"
        ));
        addMethods("javax.xml.parsers.DocumentBuilderFactory", List.of(
                "newDocumentBuilder()Ljavax/xml/parsers/DocumentBuilder;",
                "setNamespaceAware(Z)V"
        ));
        addMethods("javax.xml.parsers.SAXParserFactory", List.of(
                "newSAXParser()Ljavax/xml/parsers/SAXParser;",
                "setXIncludeAware(Z)V"
        ));

        // ====================================================================================
        // Fourth wave — tail of the XML / DOM / SAX surface plus a few remaining JDBC + util
        // leaf methods.
        // ====================================================================================
        addMethods("java.sql.Blob", List.of(
                "setBytes(J[B)I"
        ));
        addMethods("java.sql.Clob", List.of(
                "getSubString(JI)Ljava/lang/String;"
        ));
        addMethods("java.sql.DatabaseMetaData", List.of(
                "getDatabaseMinorVersion()I"
        ));
        addMethods("java.sql.Date", List.of(
                "getDate()I"
        ));
        addMethods("java.sql.ResultSet", List.of(
                "getRow()I"
        ));
        addMethods("java.sql.ResultSetMetaData", List.of(
                "getColumnTypeName(I)Ljava/lang/String;"
        ));
        addMethods("java.sql.SQLFeatureNotSupportedException", List.of(
                "<init>(Ljava/lang/String;)V"
        ));
        addMethods("java.util.Locale$Builder", List.of(
                "setRegion(Ljava/lang/String;)Ljava/util/Locale$Builder;"
        ));
        addMethods("java.util.Scanner", List.of(
                "hasNext()Z"
        ));
        addMethods("javax.xml.parsers.SAXParser", List.of(
                "parse(Ljava/io/InputStream;Lorg/xml/sax/helpers/DefaultHandler;)V"
        ));
        addMethods("org.w3c.dom.Attr", List.of(
                "getLocalName()Ljava/lang/String;"
        ));
        addMethods("org.w3c.dom.Element", List.of(
                "getAttributes()Lorg/w3c/dom/NamedNodeMap;",
                "getChildNodes()Lorg/w3c/dom/NodeList;"
        ));
        addMethods("org.w3c.dom.Node", List.of(
                "getNodeType()S"
        ));
        addMethods("org.xml.sax.InputSource", List.of(
                "<init>(Ljava/io/InputStream;)V",
                "<init>(Ljava/io/Reader;)V"
        ));

        // ====================================================================================
        // Fifth wave — the last of the DOM/SAX/JAXB surface.
        // ====================================================================================
        addMethods("java.sql.DatabaseMetaData", List.of(
                "getDatabaseProductVersion()Ljava/lang/String;"
        ));
        addMethods("java.util.Locale$Builder", List.of(
                "setVariant(Ljava/lang/String;)Ljava/util/Locale$Builder;"
        ));
        addMethods("javax.xml.parsers.DocumentBuilder", List.of(
                "setErrorHandler(Lorg/xml/sax/ErrorHandler;)V"
        ));
        addMethods("javax.xml.validation.SchemaFactory", List.of(
                "newInstance(Ljava/lang/String;)Ljavax/xml/validation/SchemaFactory;"
        ));
        addMethods("org.w3c.dom.Attr", List.of(
                "getName()Ljava/lang/String;",
                "getValue()Ljava/lang/String;"
        ));
        addMethods("org.w3c.dom.Document", List.of(
                "getDocumentElement()Lorg/w3c/dom/Element;"
        ));
        addMethods("org.w3c.dom.NamedNodeMap", List.of(
                "getLength()I",
                "item(I)Lorg/w3c/dom/Node;"
        ));
        addMethods("org.w3c.dom.NodeList", List.of(
                "getLength()I",
                "item(I)Lorg/w3c/dom/Node;"
        ));
        addMethods("org.xml.sax.InputSource", List.of(
                "getByteStream()Ljava/io/InputStream;",
                "getCharacterStream()Ljava/io/Reader;",
                "getEncoding()Ljava/lang/String;",
                "setCharacterStream(Ljava/io/Reader;)V"
        ));

        // ====================================================================================
        // Sixth wave — final stragglers.
        // ====================================================================================
        addMethods("java.util.Locale$Builder", List.of(
                "setScript(Ljava/lang/String;)Ljava/util/Locale$Builder;"
        ));
        addMethods("javax.xml.validation.SchemaFactory", List.of(
                "newSchema(Ljava/net/URL;)Ljavax/xml/validation/Schema;"
        ));
        addMethods("org.w3c.dom.Element", List.of(
                "getLocalName()Ljava/lang/String;",
                "getTagName()Ljava/lang/String;",
                "getTextContent()Ljava/lang/String;"
        ));
        addMethods("org.w3c.dom.Node", List.of(
                "getTextContent()Ljava/lang/String;"
        ));

        // ====================================================================================
        // Seventh wave — methods on the excluded-dependency leaf stubs added above.
        // ====================================================================================
        addMethods("com.beanit.jasn1.ber.BerLength", List.of(
                "skip(Ljava/io/InputStream;)I"
        ));
        addMethods("com.beanit.jasn1.ber.BerTag", List.of(
                "<init>(III)V",
                "decode(Ljava/io/InputStream;)I",
                "equals(III)Z"
        ));
        addMethods("com.beanit.jasn1.ber.ReverseByteArrayOutputStream", List.of(
                "<init>(IZ)V"
        ));
        addMethods("com.google.gson.Gson", List.of(
                "fromJson(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;",
                "toJson(Ljava/lang/Object;Ljava/lang/reflect/Type;)Ljava/lang/String;"
        ));
        addMethods("com.google.gson.GsonBuilder", List.of(
                "create()Lcom/google/gson/Gson;",
                "registerTypeHierarchyAdapter(Ljava/lang/Class;Ljava/lang/Object;)Lcom/google/gson/GsonBuilder;",
                "setPrettyPrinting()Lcom/google/gson/GsonBuilder;"
        ));
        addMethods("io.r2dbc.spi.Nullability", List.of(
                "values()[Lio/r2dbc/spi/Nullability;"
        ));
        addMethods("io.r2dbc.spi.R2dbcException", List.of(
                "<init>(Ljava/lang/Throwable;)V",
                "getSqlState()Ljava/lang/String;"
        ));
        addMethods("io.r2dbc.spi.Statement", List.of(
                "bindNull(ILjava/lang/Class;)Lio/r2dbc/spi/Statement;"
        ));
        addMethods("jakarta.xml.bind.JAXB", List.of(
                "marshal(Ljava/lang/Object;Ljava/io/Writer;)V",
                "unmarshal(Ljava/io/Reader;Ljava/lang/Class;)Ljava/lang/Object;"
        ));
        addMethods("jakarta.xml.bind.JAXBContext", List.of(
                "createMarshaller()Ljakarta/xml/bind/Marshaller;",
                "newInstance(Ljava/lang/String;)Ljakarta/xml/bind/JAXBContext;"
        ));
        addMethods("jakarta.xml.bind.annotation.XmlElement", List.of(
                "name()Ljava/lang/String;"
        ));
        addMethods("jakarta.xml.bind.annotation.XmlElementWrapper", List.of(
                "name()Ljava/lang/String;"
        ));
        addMethods("jakarta.xml.bind.annotation.XmlSchema", List.of(
                "namespace()Ljava/lang/String;"
        ));
        addMethods("jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter", List.of(
                "value()Ljava/lang/Class;"
        ));

        addMethods("com.beanit.jasn1.ber.BerLength", List.of(
                "decode(Ljava/io/InputStream;)I",
                "encodeLength(Ljava/io/OutputStream;I)I"
        ));
        addMethods("com.beanit.jasn1.ber.BerTag", List.of(
                "decodeAndCheck(Ljava/io/InputStream;)I",
                "encode(Ljava/io/OutputStream;)I"
        ));
        addMethods("com.beanit.jasn1.ber.ReverseByteArrayOutputStream", List.of(
                "getArray()[B"
        ));
        addMethods("com.beanit.jasn1.ber.types.string.BerUTF8String", List.of(
                "<init>(Ljava/lang/String;)V",
                "decode(Ljava/io/InputStream;Z)I",
                "encode(Ljava/io/OutputStream;Z)I"
        ));
        addMethods("com.google.gson.GsonBuilder", List.of(
                "serializeNulls()Lcom/google/gson/GsonBuilder;"
        ));
        addMethods("io.r2dbc.spi.R2dbcException", List.of(
                "getErrorCode()I"
        ));
        addMethods("jakarta.xml.bind.Marshaller", List.of(
                "marshal(Ljava/lang/Object;Ljava/io/Writer;)V",
                "setProperty(Ljava/lang/String;Ljava/lang/Object;)V"
        ));
        addMethods("com.beanit.jasn1.ber.types.BerInteger", List.of(
                "<init>(J)V",
                "<init>(Ljava/math/BigInteger;)V",
                "decode(Ljava/io/InputStream;Z)I",
                "encode(Ljava/io/OutputStream;Z)I"
        ));
        addMethods("com.beanit.jasn1.ber.types.BerNull", List.of(
                "decode(Ljava/io/InputStream;Z)I",
                "encode(Ljava/io/OutputStream;Z)I"
        ));
        addMethods("com.beanit.jasn1.ber.types.BerOctetString", List.of(
                "<init>([B)V",
                "decode(Ljava/io/InputStream;Z)I",
                "encode(Ljava/io/OutputStream;Z)I"
        ));
        addMethods("jakarta.xml.bind.annotation.adapters.XmlAdapter", List.of(
                "unmarshal(Ljava/lang/Object;)Ljava/lang/Object;"
        ));
        addMethods("jakarta.xml.bind.JAXBElement", List.of(
                "<init>(Ljavax/xml/namespace/QName;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Object;)V"
        ));

        // ====================================================================================
        // Field stubs — TeaVM also checks field references during reachability analysis.
        // Format: "<name>|<JVMS-descriptor>|static?"
        // ====================================================================================
        addFields("com.beanit.jasn1.ber.BerLength", List.of(
                "val|I"
        ));
        addFields("com.beanit.jasn1.ber.types.BerInteger", List.of(
                "value|Ljava/math/BigInteger;"
        ));
        addFields("com.beanit.jasn1.ber.types.BerOctetString", List.of(
                "value|[B"
        ));
        addFields("io.r2dbc.spi.Nullability", List.of(
                "NULLABLE|Lio/r2dbc/spi/Nullability;|static",
                "UNKNOWN|Lio/r2dbc/spi/Nullability;|static",
                "NON_NULL|Lio/r2dbc/spi/Nullability;|static"
        ));

        // jOOQ's `AbstractDataType.getArrayType()` calls `Class.arrayType()` at value-class
        // registration time; the buggy chain is:
        //   1. throwing UOE aborts the whole Rt_Value init chain
        //   2. returning null lets jOOQ build an ArrayDataType whose constructor then NPEs
        //      on `arrayClass.isArray()`
        // Returning `this` (the receiver Class) survives both: jOOQ sees a non-null Class,
        // its `isArray()` returns false, so the array-binding branch is skipped entirely.
        // (We can't actually produce an array class at TeaVM build time without bytecode
        // emit gymnastics; the playground never asks for the array form, so the wrong
        // identity doesn't matter.)
        addReturnThisMethods("java.lang.Class", List.of(
                "arrayType()Ljava/lang/Class;"
        ));
        addMethods("org.jooq.tools.reflect.Compile", List.of(
                "compile(Ljava/lang/String;Ljava/lang/String;Lorg/jooq/tools/reflect/CompileOptions;)Ljava/lang/Class;"
        ));
        addMethods("java.lang.reflect.GenericDeclaration", List.of(
                "getTypeParameters()[Ljava/lang/reflect/TypeVariable;"
        ));
        addFields("com.beanit.jasn1.ber.types.string.BerUTF8String", List.of(
                "tag|Lcom/beanit/jasn1/ber/BerTag;"
        ));
        addMethods("io.r2dbc.spi.Nullability", List.of(
                "ordinal()I"
        ));

        // ====================================================================================
        // Eighth wave — methods/classes surfaced by TeaVM 0.15.0-dev-2's fast-analysis
        // diagnostics. The slow-analysis path on dev-1/dev-2 NPEs in
        // ClassInfoGenerator.writeSimpleConstructors / ReflectionMetadataGenerator.generate
        // when these references can't be resolved; the dev-2 fast path reports them
        // gracefully (#1190 fix).
        // ====================================================================================
        addMethods("io.r2dbc.spi.ColumnMetadata", List.of(
                "getJavaType()Ljava/lang/Class;",
                "getName()Ljava/lang/String;",
                "getNullability()Lio/r2dbc/spi/Nullability;",
                "getPrecision()Ljava/lang/Integer;",
                "getScale()Ljava/lang/Integer;",
                "getType()Lio/r2dbc/spi/Type;"
        ));
        addMethods("io.r2dbc.spi.Row", List.of(
                "get(I)Ljava/lang/Object;",
                "get(ILjava/lang/Class;)Ljava/lang/Object;"
        ));
        addMethods("io.r2dbc.spi.Type", List.of(
                "getName()Ljava/lang/String;"
        ));
        addMethods("java.beans.Transient", List.of(
                "value()Z"
        ));
        addMethods("io.r2dbc.spi.RowMetadata", List.of(
                "getColumnMetadata(I)Lio/r2dbc/spi/ColumnMetadata;",
                "getColumnMetadatas()Ljava/util/List;"
        ));
        addMethods("io.r2dbc.spi.Statement", List.of(
                "bind(ILjava/lang/Object;)Lio/r2dbc/spi/Statement;"
        ));
        addMethods("java.sql.PreparedStatement", List.of(
                "addBatch()V"
        ));
        addMethods("java.sql.Statement", List.of(
                "clearBatch()V"
        ));
        addMethods("java.util.concurrent.atomic.AtomicReferenceArray", List.of(
                "length()I"
        ));

        // ====================================================================================
        // Ninth wave — methods surfaced by the dev-2 diagnostics after the diagnostics-driven
        // stub pass. All on stubs already shipped in `bridge/build.gradle.kts`; the dependency
        // analyser just hadn't seen these specific JDBC large-result / SAX property paths yet.
        // ====================================================================================
        addMethods("java.sql.Blob", List.of(
                "getBinaryStream()Ljava/io/InputStream;"
        ));
        addMethods("java.sql.DatabaseMetaData", List.of(
                "getSchemas(Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;"
        ));
        addMethods("java.sql.PreparedStatement", List.of(
                "executeLargeUpdate()J",
                "getLargeUpdateCount()J",
                "setLargeMaxRows(J)V",
                "setObject(ILjava/lang/Object;I)V"
        ));
        // PreparedStatement extends Statement; the analyser also probes the parent interface
        // for the same large-result methods (Statement defines them as throwing defaults).
        addMethods("java.sql.Statement", List.of(
                "getLargeUpdateCount()J",
                "setLargeMaxRows(J)V"
        ));
        addMethods("java.sql.SQLException", List.of(
                "<init>(Ljava/lang/Throwable;)V"
        ));
        addMethods("java.sql.SQLXML", List.of(
                "getString()Ljava/lang/String;"
        ));
        addMethods("javax.xml.parsers.SAXParser", List.of(
                "setProperty(Ljava/lang/String;Ljava/lang/Object;)V"
        ));

        // Rt_RellVersion.getBuildProperties() walks Class.getResource + Properties.load to
        // pull the gradle-git-properties output from `rell-base-maven.properties`. None of
        // those APIs exist in TeaVM's classlib; on the JVM they're how the playground gets
        // its version string. Replacing the body with `return null` on the TeaVM build kicks
        // the caller into FALLBACK_PROPERTIES — the only sane path in the browser — while
        // leaving upstream rell3 untouched.
        addReplaceBodyMethods("net.postchain.rell.base.runtime.Rt_RellVersion$Companion", List.of(
                "getBuildProperties()Ljava/util/Map;"
        ));
    }

    @Override
    public void transformClass(ClassHolder cls, ClassHolderTransformerContext context) {
        var isInterface = cls.hasModifier(ElementModifier.INTERFACE);

        var methodEntries = MISSING_METHODS.get(cls.getName());
        if (methodEntries != null) {
            for (var entry : methodEntries) {
                var sigStart = entry.indexOf('(');
                var name = entry.substring(0, sigStart);
                var desc = MethodDescriptor.parse(name + entry.substring(sigStart));
                if (cls.getMethod(desc) != null) continue;

                var method = new MethodHolder(desc);
                method.setLevel(AccessLevel.PUBLIC);
                if (!isInterface && !"<init>".equals(name)) {
                    method.getModifiers().add(ElementModifier.FINAL);
                }
                var key = cls.getName() + "#" + entry;
                if (RETURN_THIS_METHODS.contains(key)) {
                    method.setProgram(buildReturnThisStub(method, context, cls.getName()));
                } else {
                    method.setProgram(buildThrowStub(method, context));
                }
                cls.addMethod(method);
            }
        }

        var fieldEntries = MISSING_FIELDS.get(cls.getName());
        if (fieldEntries != null) {
            for (var entry : fieldEntries) {
                var parts = entry.split("\\|");
                var name = parts[0];
                var descriptor = parts[1];
                var isStatic = parts.length > 2 && "static".equals(parts[2]);
                if (cls.getField(name) != null) continue;

                var field = new FieldHolder(name);
                field.setLevel(AccessLevel.PUBLIC);
                field.setType(ValueType.parse(descriptor));
                if (isStatic) field.getModifiers().add(ElementModifier.STATIC);
                cls.addField(field);
            }
        }

        // REPLACE_BODY_METHODS: overwrite the bodies of methods that already exist on this
        // class with a silent return-default stub. The original bytecode (which may reference
        // JVM-only classes like java.util.Properties or sun.* internals) never enters the
        // dependency graph, so reachability analysis does not pull those classes in.
        // `MethodDescriptor.toString()` already includes the method name + signature, e.g.
        // "getBuildProperties()Ljava/util/Map;", so we do NOT double-prefix the name.
        for (var method : cls.getMethods()) {
            var key = cls.getName() + "#" + method.getDescriptor().toString();
            if (REPLACE_BODY_METHODS.contains(key)) {
                method.getModifiers().remove(ElementModifier.NATIVE);
                method.setProgram(buildSilentStub(method, context));
            }
        }
    }

    /**
     * Builds a program body equivalent to:
     *
     *     throw new UnsupportedOperationException("not in TeaVM: " + className + "." + methodName);
     *
     * via [ProgramEmitter], which handles variable allocation and basic-block plumbing.
     */
    private static org.teavm.model.Program buildThrowStub(MethodHolder method,
                                                          ClassHolderTransformerContext context) {
        var emitter = ProgramEmitter.create(method, context.getHierarchy());
        emitter.construct(UnsupportedOperationException.class,
                emitter.constant("not in TeaVM: " + method.getOwnerName() + "." + method.getName()))
                .raise();
        return emitter.getProgram();
    }

    /**
     * Builds a program body that silently returns the type's default value (`null` for
     * objects, `0` / `0.0` / `false` for primitives, no value for void). Used for methods
     * whose downstream callers treat `null`/zero as "feature unavailable" — e.g.
     * `java.lang.Class.arrayType()` called by jOOQ's `AbstractDataType.getArrayType()`,
     * where throwing UOE would abort the whole Rell value-class registration.
     */
    /**
     * Body that returns the receiver: `return this`. Only valid for instance methods whose
     * declared return type is assignable from the declaring class.
     */
    private static org.teavm.model.Program buildReturnThisStub(MethodHolder method,
                                                               ClassHolderTransformerContext context,
                                                               String className) {
        var emitter = ProgramEmitter.create(method, context.getHierarchy());
        // Parameter 0 of every instance method is `this`; ProgramEmitter.var(0, ...) wraps it.
        emitter.var(0, ValueType.object(className)).returnValue();
        return emitter.getProgram();
    }

    private static org.teavm.model.Program buildSilentStub(MethodHolder method,
                                                           ClassHolderTransformerContext context) {
        var emitter = ProgramEmitter.create(method, context.getHierarchy());
        var ret = method.getResultType();
        if (ret == ValueType.VOID) {
            emitter.exit();
        } else if (ret instanceof ValueType.Primitive prim) {
            switch (prim.getKind()) {
                case BOOLEAN, BYTE, SHORT, CHARACTER, INTEGER -> emitter.constant(0).returnValue();
                case LONG -> emitter.constant(0L).returnValue();
                case FLOAT -> emitter.constant(0F).returnValue();
                case DOUBLE -> emitter.constant(0D).returnValue();
            }
        } else {
            // Object or array: return null cast to the declared type.
            emitter.constantNull(ret).returnValue();
        }
        return emitter.getProgram();
    }
}
