import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.teavm.gradle.api.JSModuleType
import org.teavm.gradle.api.OptimizationLevel

buildscript {
    // ASM in the build classpath, used by the `generateTeavmStubs` task to emit empty stub
    // classes in packages we can't normally compile into from Kotlin sources (java.*, jakarta.*).
    repositories { mavenCentral() }
    dependencies {
        classpath("org.ow2.asm:asm:9.10.1")
    }
}

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.teavm)
}

description =
    "Kotlin/JVM bridge for the playground. Compiled to JS by TeaVM; exposes runFile / replCreate / replExecute as static @JSExport methods that the SPA worker invokes through ESM import."

kotlin.compilerOptions {
    jvmTarget = JvmTarget.JVM_21
    optIn.add("net.postchain.rell.api.base.InternalRellApi")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

// ---- TeaVM stubs ---------------------------------------------------------------------------
//
// TeaVM's classlib emulates ~30 JDK packages but ships no java.sql.*, java.beans.*, javax.xml.*,
// jakarta.persistence.*, etc. — and we can't compile classes into restricted packages (`java.*`)
// from Kotlin sources. The fix is a small JAR of generated bytecode placed *first* on the TeaVM
// classpath so its empty stub definitions satisfy reachability analysis for jOOQ / Jackson /
// SLF4J etc. that reference these types only at compile time.
//
// None of the stubbed classes are actually called at runtime in the browser dry-run path:
// CapturingSqlExecutor throws before touching JDBC, log calls go through kotlin-logging's
// no-op SLF4J binding, and Rell's JSON type only triggers when a Rell program uses `json`.
//
// Each stub is an empty interface (for types that look like interfaces) or an empty class with
// a public no-arg constructor (for the rest). TeaVM dead-code-eliminates them aggressively.

data class Stub(val name: String, val isInterface: Boolean = true)

// Generated stub class names are rewritten from `<pkg>/X` (or `<pkg>/X$Inner`) into
// `org/teavm/classlib/<pkg>/TX` (or `org/teavm/classlib/<pkg>/TX$Inner`) so teavm-classlib's
// existing T-prefix package renamer (`mapPackageHierarchy|org.teavm.classlib.java=java` +
// `stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.java=T`) translates them back to
// `<pkg>/X` at TeaVM's class-loading layer. This sidesteps the URLClassLoader parent-first
// delegation that would otherwise route every `java.*` lookup through the JDK's bootstrap
// loader and import JDK bytecode (with its full cascade of inner-class / native-method
// references) instead of our empty stubs.
//
// For non-java.* packages (jakarta, javax) we add equivalent mapping rules in
// META-INF/teavm.properties.

fun stubInternalName(name: String): String {
    // Split "<pkg>/<Class>$Inner" into ("<pkg>/", "<Class>$Inner").
    val lastSlash = name.lastIndexOf('/')
    val pkg = name.substring(0, lastSlash)
    val cls = name.substring(lastSlash + 1)
    return "org/teavm/classlib/$pkg/T$cls"
}

val stubs = listOf(
    // jakarta.persistence — JPA annotations referenced by jOOQ's optional bean-mapping path.
    Stub("jakarta/persistence/Column", isInterface = true),
    Stub("jakarta/persistence/Entity", isInterface = true),
    Stub("jakarta/persistence/Id", isInterface = true),
    Stub("jakarta/persistence/Table", isInterface = true),

    // java.beans — JavaBeans introspection used by jOOQ's record-mapping path.
    Stub("java/beans/ConstructorProperties", isInterface = true),
    // Jackson's reflection probe walks @Transient; without it, dev-2's `fast=true`
    // dependency analyser reports "Class java.beans.Transient was not found".
    Stub("java/beans/Transient", isInterface = true),

    // java.sql — JDBC. Referenced by jOOQ everywhere; the no-conn executor throws before any
    // call site is actually exercised at runtime.
    Stub("java/sql/Array"),
    Stub("java/sql/Blob"),
    Stub("java/sql/Clob"),
    Stub("java/sql/Connection"),
    Stub("java/sql/DatabaseMetaData"),
    Stub("java/sql/Date", isInterface = false),
    Stub("java/sql/DriverManager", isInterface = false),
    Stub("java/sql/PreparedStatement"),
    Stub("java/sql/ResultSet"),
    Stub("java/sql/ResultSetMetaData"),
    Stub("java/sql/SQLException", isInterface = false),
    Stub("java/sql/SQLWarning", isInterface = false),
    Stub("java/sql/Statement"),
    Stub("java/sql/Struct"),
    Stub("java/sql/Time", isInterface = false),
    Stub("java/sql/Timestamp", isInterface = false),
    Stub("java/sql/Wrapper"),
    Stub("java/sql/CallableStatement"),
    Stub("java/sql/Driver"),
    Stub("java/sql/DriverPropertyInfo", isInterface = false),
    Stub("java/sql/ParameterMetaData"),
    Stub("java/sql/Ref"),
    Stub("java/sql/RowId"),
    Stub("java/sql/SQLClientInfoException", isInterface = false),
    Stub("java/sql/SQLData"),
    Stub("java/sql/SQLDataException", isInterface = false),
    Stub("java/sql/SQLInput"),
    Stub("java/sql/SQLIntegrityConstraintViolationException", isInterface = false),
    Stub("java/sql/SQLInvalidAuthorizationSpecException", isInterface = false),
    Stub("java/sql/SQLNonTransientConnectionException", isInterface = false),
    Stub("java/sql/SQLOutput"),
    Stub("java/sql/SQLPermission", isInterface = false),
    Stub("java/sql/SQLRecoverableException", isInterface = false),
    Stub("java/sql/SQLSyntaxErrorException", isInterface = false),
    Stub("java/sql/SQLTimeoutException", isInterface = false),
    Stub("java/sql/SQLTransactionRollbackException", isInterface = false),
    Stub("java/sql/SQLTransientConnectionException", isInterface = false),
    Stub("java/sql/SQLXML"),
    Stub("java/sql/Types", isInterface = false),

    // java.lang — selected error/marker classes not in TeaVM's classlib.
    Stub("java/lang/BootstrapMethodError", isInterface = false),
    Stub("java/lang/ClassCircularityError", isInterface = false),
    Stub("java/lang/ClassFormatError", isInterface = false),
    Stub("java/lang/Module", isInterface = false),
    Stub("java/lang/RuntimePermission", isInterface = false),
    Stub("java/lang/StackWalker", isInterface = false),
    Stub("java/lang/VerifyError", isInterface = false),

    // java.lang.reflect — reflection types referenced by jackson-databind / kotlin-reflect deep paths.
    Stub("java/lang/reflect/GenericArrayType", isInterface = true),
    Stub("java/lang/reflect/ParameterizedType", isInterface = true),
    Stub("java/lang/reflect/Proxy", isInterface = false),
    Stub("java/lang/reflect/TypeVariable", isInterface = true),
    Stub("java/lang/reflect/WildcardType", isInterface = true),

    // java.net — URLClassLoader is touched by SLF4J's class loading.
    Stub("java/net/URLClassLoader", isInterface = false),

    // java.security — postchain crypto's MessageDigest call is on a path the bridge doesn't trigger.
    Stub("java/security/MessageDigest", isInterface = false),
    Stub("java/security/Security", isInterface = false),

    // java.util — Scanner/HexFormat/LinkedBlockingQueue/AtomicLongArray are leaf JDK classes
    // referenced only in static-init paths inside third-party libs we don't actually call.
    Stub("java/util/HexFormat", isInterface = false),
    Stub("java/util/Scanner", isInterface = false),
    Stub("java/util/concurrent/LinkedBlockingQueue", isInterface = false),
    Stub("java/util/concurrent/atomic/AtomicIntegerArray", isInterface = false),
    Stub("java/util/concurrent/atomic/AtomicLongArray", isInterface = false),
    Stub("java/util/concurrent/locks/Lock", isInterface = true),
    Stub("java/util/concurrent/locks/ReadWriteLock", isInterface = true),
    Stub("java/util/concurrent/locks/ReentrantLock", isInterface = false),
    Stub("java/util/concurrent/locks/ReentrantReadWriteLock", isInterface = false),

    // javax.xml — pulled in by jaxb / jOOQ.
    Stub("javax/xml/namespace/QName", isInterface = false),
    Stub("javax/xml/parsers/DocumentBuilder", isInterface = false),
    Stub("javax/xml/parsers/DocumentBuilderFactory", isInterface = false),
    Stub("javax/xml/parsers/SAXParserFactory", isInterface = false),
    Stub("javax/xml/datatype/DatatypeFactory", isInterface = false),
    Stub("javax/xml/datatype/Duration", isInterface = false),
    Stub("javax/xml/transform/Result", isInterface = true),
    Stub("javax/xml/transform/Source", isInterface = true),
    Stub("javax/xml/transform/TransformerFactory", isInterface = false),
    Stub("javax/xml/transform/dom/DOMResult", isInterface = false),
    Stub("javax/xml/transform/dom/DOMSource", isInterface = false),
    Stub("javax/xml/transform/sax/SAXResult", isInterface = false),
    Stub("javax/xml/transform/sax/SAXSource", isInterface = false),
    Stub("javax/xml/transform/sax/SAXTransformerFactory", isInterface = false),
    Stub("javax/xml/transform/stream/StreamResult", isInterface = false),
    Stub("javax/xml/transform/stream/StreamSource", isInterface = false),
    Stub("javax/xml/validation/Schema", isInterface = false),

    // java.io — Jackson's optional serialization path references these even when we don't
    // serialize anything binary. Stubbing satisfies reachability.
    Stub("java/io/FilePermission", isInterface = false),
    Stub("java/io/ObjectInputStream", isInterface = false),
    Stub("java/io/ObjectStreamClass", isInterface = false),
    Stub("java/io/ObjectStreamField", isInterface = false),

    // java.lang — more exceptions, modular-runtime classes, $-nested inner classes.
    Stub("java/lang/ExceptionInInitializerError", isInterface = false),
    Stub("java/lang/IllegalCallerException", isInterface = false),
    Stub("java/lang/InstantiationError", isInterface = false),
    Stub($$"java/lang/Module$ArchivedData", isInterface = false),
    Stub("java/lang/StackStreamFactory", isInterface = false),
    Stub($$"java/lang/StackWalker$Option", isInterface = false),
    Stub("java/lang/ThreadGroup", isInterface = false),
    Stub("java/lang/TypeNotPresentException", isInterface = false),
    Stub("java/lang/UnsatisfiedLinkError", isInterface = false),

    Stub("java/lang/invoke/VarHandle", isInterface = false),
    Stub("java/lang/management/ManagementFactory", isInterface = false),
    Stub("java/lang/module/ModuleDescriptor", isInterface = false),
    Stub("java/lang/module/ModuleReader", isInterface = true),
    Stub("java/lang/module/ModuleReference", isInterface = false),
    Stub("java/lang/ref/Cleaner", isInterface = false),
    Stub("java/lang/ref/PhantomReference", isInterface = false),

    // java.net — Jackson/jOOQ network code paths.
    Stub("java/net/InetAddress", isInterface = false),
    Stub("java/net/InetSocketAddress", isInterface = false),
    Stub("java/net/JarURLConnection", isInterface = false),
    Stub("java/net/NetPermission", isInterface = false),
    Stub("java/net/Socket", isInterface = false),
    Stub("java/net/SocketPermission", isInterface = false),
    Stub("java/net/SocketTimeoutException", isInterface = false),

    // java.nio — file-system interaction is dead code in a browser.
    Stub("java/nio/channels/Channels", isInterface = false),

    // java.util — various reflection / serialisation leaf classes + nested $ classes.
    Stub("java/util/InputMismatchException", isInterface = false),
    Stub($$"java/util/Locale$Builder", isInterface = false),
    Stub($$"java/util/Scanner$PatternLRUCache", isInterface = false),
    Stub("java/util/SimpleTimeZone", isInterface = false),
    Stub("java/util/StringJoiner", isInterface = false),
    Stub("java/util/concurrent/ConcurrentLinkedQueue", isInterface = false),
    Stub("java/util/concurrent/ConcurrentNavigableMap", isInterface = true),
    Stub("java/util/concurrent/ConcurrentSkipListMap", isInterface = false),
    Stub("java/util/concurrent/ForkJoinPool", isInterface = false),
    Stub("java/util/concurrent/Helpers", isInterface = false),
    Stub($$"java/util/concurrent/LinkedBlockingQueue$Itr", isInterface = false),
    Stub($$"java/util/concurrent/LinkedBlockingQueue$Node", isInterface = false),
    Stub("java/util/concurrent/StructureViolationException", isInterface = false),
    Stub("java/util/concurrent/atomic/AtomicReferenceArray", isInterface = false),

    // Third-wave classes discovered after the second build pass.
    Stub("java/awt/Image", isInterface = false),
    Stub("java/beans/Introspector", isInterface = false),
    Stub("java/lang/reflect/Parameter", isInterface = false),
    Stub("java/lang/reflect/RecordComponent", isInterface = false),
    Stub("java/lang/reflect/GenericDeclaration", isInterface = true),
    Stub("java/lang/ModuleLayer", isInterface = false),
    Stub($$"java/lang/StackStreamFactory$AbstractStackWalker", isInterface = false),
    Stub($$"java/lang/StackStreamFactory$LiveStackInfoTraverser", isInterface = false),
    Stub($$"java/lang/StackStreamFactory$StackFrameTraverser", isInterface = false),
    Stub("java/net/Inet6Address", isInterface = false),
    Stub("java/nio/MappedByteBuffer", isInterface = false),
    Stub("java/security/BasicPermission", isInterface = false),
    Stub("java/util/concurrent/AbstractExecutorService", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentLinkedQueue$Itr", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentLinkedQueue$Node", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentSkipListMap$EntrySet", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentSkipListMap$Index", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentSkipListMap$KeySet", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentSkipListMap$Node", isInterface = false),
    Stub($$"java/util/concurrent/ConcurrentSkipListMap$Values", isInterface = false),
    Stub("java/util/concurrent/ConcurrentSkipListSet", isInterface = false),
    Stub($$"java/util/concurrent/ForkJoinPool$1", isInterface = false),
    Stub($$"java/util/concurrent/ForkJoinPool$2", isInterface = false),
    Stub($$"java/util/concurrent/ForkJoinPool$DefaultForkJoinWorkerThreadFactory", isInterface = false),
    Stub($$"java/util/concurrent/ForkJoinPool$WorkQueue", isInterface = false),
    Stub("java/util/concurrent/ForkJoinWorkerThread", isInterface = false),
    Stub("java/util/concurrent/LinkedTransferQueue", isInterface = false),
    Stub("java/util/concurrent/ThreadFactory", isInterface = true),
    Stub("java/util/logging/ConsoleHandler", isInterface = false),
    Stub("javax/xml/datatype/XMLGregorianCalendar", isInterface = false),

    // Fourth-wave classes — referenced by jOOQ's XML config + mini-JAXB + JDBC error handling.
    Stub("java/security/CodeSource", isInterface = false),
    Stub("java/security/ProtectionDomain", isInterface = false),
    Stub("java/sql/SQLFeatureNotSupportedException", isInterface = false),
    Stub("java/sql/Savepoint", isInterface = true),
    Stub("javax/xml/namespace/NamespaceContext", isInterface = true),
    Stub("javax/xml/parsers/FactoryConfigurationError", isInterface = false),
    Stub("javax/xml/parsers/SAXParser", isInterface = false),
    Stub("javax/xml/transform/Transformer", isInterface = false),
    Stub("javax/xml/transform/sax/TransformerHandler", isInterface = true),
    Stub("javax/xml/validation/SchemaFactory", isInterface = false),
    Stub("javax/xml/validation/ValidatorHandler", isInterface = false),

    // org.w3c.dom + org.xml.sax — referenced by javax.xml.parsers / .transform interfaces.
    // These live outside java.*/javax.* and don't need the T-prefix renamer; but our stub
    // generator just produces empty interfaces with the same `org.teavm.classlib.<pkg>.T<C>`
    // path, then a one-line teavm.properties entry below remaps them.
    Stub("org/w3c/dom/Document", isInterface = true),
    Stub("org/w3c/dom/Node", isInterface = true),
    Stub("org/w3c/dom/Attr", isInterface = true),
    Stub("org/w3c/dom/Element", isInterface = true),
    Stub("org/w3c/dom/NamedNodeMap", isInterface = true),
    Stub("org/w3c/dom/NodeList", isInterface = true),
    Stub("org/xml/sax/ContentHandler", isInterface = true),
    Stub("org/xml/sax/InputSource", isInterface = false),
    Stub("org/xml/sax/XMLReader", isInterface = true),
    Stub("org/xml/sax/Attributes", isInterface = true),
    Stub("org/xml/sax/ErrorHandler", isInterface = true),
    Stub("org/xml/sax/Locator", isInterface = true),
    Stub("org/xml/sax/helpers/DefaultHandler", isInterface = false),
    Stub("org/xml/sax/ext/LexicalHandler", isInterface = true),
    Stub("java/nio/file/FileStore", isInterface = false),
    Stub("java/nio/file/WatchService", isInterface = true),
    Stub("java/util/logging/Handler", isInterface = false),
    Stub("org/w3c/dom/Text", isInterface = true),

    // jOOQ pulls in glassfish-jaxb optional path via reflection — stub the one interface it
    // hits at link time (the runtime path never reaches `LocatorEx.getColumnNumber` because
    // the playground doesn't drive XML config files into jOOQ).
    Stub("org/glassfish/jaxb/core/v2/runtime/unmarshaller/LocatorEx", isInterface = true),
    // GtvMLEscapeHandler implements this — same WasmGC vtable NPE cause as the Gson pair
    // above (konsoletyper/teavm#1188 maintainer comment).
    Stub("org/glassfish/jaxb/core/marshaller/CharacterEscapeHandler", isInterface = true),
    Stub("jakarta/xml/bind/ValidationEventLocator", isInterface = true),

    // Seventh wave — leaves of dependencies we excluded at the Gradle level but whose names
    // still appear in bytecode of classes that DO end up on the classpath (jOOQ references
    // jaxb internals; postchain-common references jasn1 / gson). Empty stubs satisfy the
    // analyser; the call sites aren't reachable from REPL/bridge entry points.
    Stub("com/beanit/jasn1/ber/BerLength", isInterface = false),
    Stub("com/beanit/jasn1/ber/BerTag", isInterface = false),
    Stub("com/beanit/jasn1/ber/ReverseByteArrayOutputStream", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/string/BerUTF8String", isInterface = false),
    Stub("com/google/gson/Gson", isInterface = false),
    Stub("com/google/gson/GsonBuilder", isInterface = false),
    // GtvAdapter implements these — without them WasmGC's vtable builder NPEs when
    // wiring the GtvAdapter's interface implementor list (konsoletyper/teavm#1188).
    Stub("com/google/gson/JsonDeserializer", isInterface = true),
    Stub("com/google/gson/JsonSerializer", isInterface = true),
    Stub("io/r2dbc/spi/Nullability", isInterface = false),
    Stub("io/r2dbc/spi/R2dbcException", isInterface = false),
    Stub("io/r2dbc/spi/Statement", isInterface = true),
    Stub("io/r2dbc/spi/ConnectionFactory", isInterface = true),
    Stub("io/r2dbc/spi/Connection", isInterface = true),
    Stub("io/r2dbc/spi/Result", isInterface = true),
    Stub("io/r2dbc/spi/Row", isInterface = true),
    Stub("io/r2dbc/spi/RowMetadata", isInterface = true),
    Stub("io/r2dbc/spi/ColumnMetadata", isInterface = true),
    // Return type of ColumnMetadata.getType(); dev-2 fast-analysis flags it as missing.
    Stub("io/r2dbc/spi/Type", isInterface = true),
    Stub("io/r2dbc/spi/Batch", isInterface = true),
    Stub("io/r2dbc/spi/ConnectionFactoryMetadata", isInterface = true),
    Stub("io/r2dbc/spi/Closeable", isInterface = true),
    Stub("io/r2dbc/spi/Publisher", isInterface = true),
    Stub("org/reactivestreams/Publisher", isInterface = true),
    Stub("org/reactivestreams/Subscriber", isInterface = true),
    Stub("org/reactivestreams/Subscription", isInterface = true),
    Stub("jakarta/xml/bind/JAXB", isInterface = false),
    Stub("jakarta/xml/bind/JAXBContext", isInterface = false),
    Stub("jakarta/xml/bind/annotation/XmlElement", isInterface = true),
    Stub("jakarta/xml/bind/annotation/XmlElementWrapper", isInterface = true),
    Stub("jakarta/xml/bind/annotation/XmlEnum", isInterface = true),
    Stub("jakarta/xml/bind/annotation/XmlSchema", isInterface = true),
    Stub("jakarta/xml/bind/annotation/XmlType", isInterface = true),
    Stub("jakarta/xml/bind/annotation/adapters/XmlJavaTypeAdapter", isInterface = true),
    Stub("jakarta/xml/bind/annotation/XmlList", isInterface = true),
    Stub("jakarta/xml/bind/Marshaller", isInterface = true),
    Stub("jakarta/xml/bind/annotation/adapters/XmlAdapter", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/BerInteger", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/BerNull", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/BerOctetString", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/BerType", isInterface = true),
    Stub("com/beanit/jasn1/ber/types/BerBoolean", isInterface = false),
    Stub("com/beanit/jasn1/ber/types/BerEnum", isInterface = false),
    Stub("com/beanit/jasn1/ber/ReverseBerEncoder", isInterface = false),
    Stub("com/beanit/jasn1/ber/internal/Util", isInterface = false),
    Stub("jakarta/xml/bind/JAXBElement", isInterface = false),

    // jOOQ runtime Java compiler — references MethodHandles.Lookup.defineClass([B)Ljava/lang/Class;
    // which trips a TeaVM 0.12 bug ("Illegal type signature: [java/lang/Class;") deep in its
    // array-of-Class signature handling. We're not invoking the runtime compiler in the
    // browser, so replacing the class with an empty stub side-steps the bug entirely.
    Stub("org/jooq/tools/reflect/Compile", isInterface = false),
    Stub("org/jooq/tools/reflect/CompileOptions", isInterface = false),
)

val stubsClassesDir = layout.buildDirectory.dir("generated/teavm-stubs/classes")

// TeaVM's classlib jar ships `META-INF/teavm.properties` with the directive
// `includePackageHierarchy|java=false` — meaning every classpath entry whose class names start
// with `java.` is *excluded* by default (TeaVM expects to provide them itself, via the
// `org.teavm.classlib.java.*` → `java.*` renaming). Our stubs jar carries an additional
// `META-INF/teavm.properties` that *re-includes* the specific java.* / jakarta.* / javax.*
// sub-packages we ship stubs for, so the renamer doesn't drop them on the floor.
val teavmStubsIncludes = listOf(
    // Mapping rules so my generated `org.teavm.classlib.<pkg>.T<Class>` stubs surface as the
    // requested `<pkg>.<Class>` classes. teavm-classlib already ships these for `java.*`; the
    // jakarta.* and javax.* lines below add equivalent prefixes for the packages it doesn't
    // cover. Package-hierarchy rules cascade to sub-packages.
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.jakarta=T",
    "mapPackageHierarchy|org.teavm.classlib.jakarta=jakarta",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.javax=T",
    "mapPackageHierarchy|org.teavm.classlib.javax=javax",
    // org.w3c.* and org.xml.* — same shape, distinct package roots.
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.w3c=T",
    "mapPackageHierarchy|org.teavm.classlib.org.w3c=org.w3c",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.xml=T",
    "mapPackageHierarchy|org.teavm.classlib.org.xml=org.xml",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.glassfish=T",
    "mapPackageHierarchy|org.teavm.classlib.org.glassfish=org.glassfish",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.jakarta.xml=T",
    "mapPackageHierarchy|org.teavm.classlib.jakarta.xml=jakarta.xml",
    // com.beanit, com.google.gson, io.r2dbc — leaf libraries we excluded from the dep graph;
    // these prefixes let the stubs surface where TeaVM expects to find the original classes.
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.com.beanit=T",
    "mapPackageHierarchy|org.teavm.classlib.com.beanit=com.beanit",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.com.google=T",
    "mapPackageHierarchy|org.teavm.classlib.com.google=com.google",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.io.r2dbc=T",
    "mapPackageHierarchy|org.teavm.classlib.io.r2dbc=io.r2dbc",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.jooq=T",
    "mapPackageHierarchy|org.teavm.classlib.org.jooq=org.jooq",
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.reactivestreams=T",
    "mapPackageHierarchy|org.teavm.classlib.org.reactivestreams=org.reactivestreams",
    // SLF4J shim: org.teavm.classlib.org.slf4j.TLoggerFactory → org.slf4j.LoggerFactory.
    // Replaces SLF4J's real LoggerFactory whose provider-discovery static init would
    // otherwise abort the moment any rell-base `companion object: KLogging()` resolves.
    "stripPrefixFromPackageHierarchyClasses|org.teavm.classlib.org.slf4j=T",
    "mapPackageHierarchy|org.teavm.classlib.org.slf4j=org.slf4j",
    // teavm-classlib excludes javax.xml from project-classpath lookups by default
    // (`includePackageHierarchy|javax.xml=false`); the rename above re-enables it for the
    // sub-tree we ship stubs for.
    "includePackageHierarchy|javax.xml=true",
)

val generateTeavmStubs by tasks.registering {
    description = "Emits empty stub bytecode for JDK packages TeaVM's classlib omits."
    group = LifecycleBasePlugin.BUILD_GROUP

    inputs.property("stubs", stubs.joinToString { "${it.name}|${it.isInterface}" })
    inputs.property("includes", teavmStubsIncludes.joinToString("\n"))
    outputs.dir(stubsClassesDir)

    doLast {
        // Java 11 class version: V11 = 55. TeaVM is happy with anything <= 21.
        val classVersion = 55
        val outDir = stubsClassesDir.get().asFile
        outDir.deleteRecursively()
        outDir.mkdirs()

        for (stub in stubs) {
            val internalName = stubInternalName(stub.name)
            val cw = org.objectweb.asm.ClassWriter(0)
            val access = if (stub.isInterface) {
                org.objectweb.asm.Opcodes.ACC_PUBLIC or
                        org.objectweb.asm.Opcodes.ACC_INTERFACE or
                        org.objectweb.asm.Opcodes.ACC_ABSTRACT
            } else {
                org.objectweb.asm.Opcodes.ACC_PUBLIC or org.objectweb.asm.Opcodes.ACC_SUPER
            }
            cw.visit(classVersion, access, internalName, null, "java/lang/Object", null)
            if (!stub.isInterface) {
                // Public no-arg constructor: super(); return;
                val mv = cw.visitMethod(org.objectweb.asm.Opcodes.ACC_PUBLIC, "<init>", "()V", null, null)
                mv.visitCode()
                mv.visitVarInsn(org.objectweb.asm.Opcodes.ALOAD, 0)
                mv.visitMethodInsn(
                    org.objectweb.asm.Opcodes.INVOKESPECIAL,
                    "java/lang/Object",
                    "<init>",
                    "()V",
                    false,
                )
                mv.visitInsn(org.objectweb.asm.Opcodes.RETURN)
                mv.visitMaxs(1, 1)
                mv.visitEnd()
            }
            cw.visitEnd()
            val classFile = outDir.resolve("$internalName.class")
            classFile.parentFile.mkdirs()
            classFile.writeBytes(cw.toByteArray())
        }

        // teavm.properties: re-includes the java.* / jakarta.* / javax.* sub-packages we ship.
        val propsFile = outDir.resolve("META-INF/teavm.properties")
        propsFile.parentFile.mkdirs()
        propsFile.writeText(teavmStubsIncludes.joinToString("\n", postfix = "\n"))
    }
}

// Pack the stubs into a JAR so we can prepend it to the TeaVM classpath.
val teavmStubsJar by tasks.registering(Jar::class) {
    description = "Packages TeaVM JDK-stub bytecode into a JAR."
    group = LifecycleBasePlugin.BUILD_GROUP
    dependsOn(generateTeavmStubs)
    from(stubsClassesDir)
    archiveBaseName = "teavm-stubs"
    destinationDirectory = layout.buildDirectory.dir("generated/teavm-stubs")
}

dependencies {
    // Stubs jar must come before rell-base so TeaVM picks our (empty) java.sql.Connection etc.
    // before any other classpath entry that declares them transitively.
    implementation(files(teavmStubsJar.flatMap { it.archiveFile }))

    // The playground only uses the compiler + interpreter + REPL surface in `rell-base` and the
    // glue constants in `rell-api-base`. `rell-tools` (CLI), `rell-api-shell` (shell driver),
    // `rell-api-gtx` (GTX/postchain client), and `rell-gtx` would each drag in tens of
    // megabytes of transitive deps (postgres JDBC, gRPC, jackson, hikari, jline, …) that have
    // nothing to do with running a REPL — TeaVM would spend its reachability budget trying to
    // link them.
    //
    // The `exclude(...)` block below cuts dead-weight transitive dependencies that postchain
    // drags in but no playground code path touches. Each was reached only through static-init
    // chains that the dependency analyser kept widening. Excluding them at the Gradle level
    // is cleaner than chasing every leaf method via the TeaVM stub plugin.
    configurations.named("implementation").configure {
        // Cut dead-weight transitive deps that postchain drags in but no playground code path
        // touches. Each was reached only through static-init chains that TeaVM's dependency
        // analyser kept widening. Excluding them here is cleaner than chasing every leaf
        // method via the TeaVM stub plugin.
        exclude(group = "com.sun.xml.bind")                  // jaxb-impl / jaxb-core — XML binding
        exclude(group = "jakarta.xml.bind")                  // jakarta JAXB API
        exclude(group = "jakarta.activation")                // jakarta.activation-api
        exclude(group = "org.eclipse.angus")                 // angus-activation impl
        exclude(group = "com.beanit", module = "jasn1")      // ASN.1 codecs (postchain crypto path we don't reach)
        exclude(group = "org.graalvm.truffle")               // Truffle backend for rell-base (JVM-only)
        exclude(group = "org.graalvm.polyglot")
        exclude(group = "org.graalvm.sdk")
        exclude(group = "net.postchain.rell", module = "runtime-truffle")
        exclude(group = "io.r2dbc")                          // R2DBC reactive JDBC
        exclude(group = "org.reactivestreams")
        exclude(group = "org.postgresql")                    // PostgreSQL JDBC driver — no DB in browser
        exclude(group = "com.google.code.gson")              // gson — postchain uses it, we don't
    }

    implementation(libs.rell.api.base)

    // teavm-jso brings the @JSExport annotation used to expose static Kotlin methods to JS.
    // The annotation has no runtime semantics on JVM; TeaVM consumes it at compile time.
    compileOnly(libs.teavm.jso)

    // teavm-core: needed to compile the TeaVMPlugin / ClassHolderTransformer at
    // com.chromia.rellplayground.teavm.*. Marked `compileOnly` because the plugin classes are
    // loaded by TeaVM's own daemon (which already has teavm-core on its classpath) — shipping
    // teavm-core itself into the compiled output would bloat the JS bundle with classes TeaVM
    // never reaches at runtime.
    compileOnly(libs.teavm.core)

    // TeaVM classpath. teavm(...) adds the entry to the configuration TeaVM compiles from
    // (in addition to runtimeClasspath). jsoApis provides DOM + JSON types — we use a small
    // subset (e.g. nothing yet) but it's required for the JS frontend's helpers.
    teavm(libs.teavm.jso.apis)
}

// Tensor-probe parameters. Override on the CLI with -Prell.teavm.opt=BALANCED, -Prell.teavm.fast=true.
val probeOpt: OptimizationLevel = (project.findProperty("rell.teavm.opt") as String?)
    ?.let { OptimizationLevel.valueOf(it) } ?: OptimizationLevel.NONE
val probeFast: Boolean = (project.findProperty("rell.teavm.fast") as String?)?.toBoolean() ?: false

teavm {
    all {
        // TeaVM compiles a JVM `main(String[])` entry point. Everything else reachable from
        // it (or from @JSExport methods on the same module) is included.
        mainClass = "com.chromia.rellplayground.PlaygroundJsBridge"
        // Pin every @JSExport-bearing class — without an explicit reference from `main`,
        // TeaVM's dead-code elimination would drop them before the JSExport transformer runs.
        fastGlobalAnalysis = probeFast
        preservedClasses.add("com.chromia.rellplayground.PlaygroundJsBridge")
    }
    js {
        // ESM output — the SPA worker imports the generated module directly.
        moduleType = JSModuleType.ES2015
        optimization = probeOpt
        // Run TeaVM in a forked JVM. The classlib + reachability analysis routinely needs many
        // GB of heap on rell-base + its transitive deps; running in-process competes with
        // Gradle's daemon heap. 8 GB is what the slow dependency-propagation pass needs to
        // converge without thrashing GC.
        outOfProcess = true
        processMemory = 8192
        // Obfuscation halves the minified size — critical for Safari, whose WebKit parser
        // silently stalls compiling our ~90 MB unminified bridge module inside a worker.
        // Variable-name shortening is the cheapest win we have.
        obfuscated = true
        // Sourcemap is a ~50 MB sibling we don't need in production. Keep it off; the stack
        // traces TeaVM emits already carry Kotlin file/line via @SourceFile attributes.
        sourceMap = false
        targetFileName = "rell-playground-bridge.js"
    }
    // WasmGC backend probe — exploring whether 0.15.0-dev-N's WasmGC target compiles where
    // the JS backend currently NPEs (konsoletyper/teavm#1189). Run with ./gradlew :bridge:generateWasmGC.
    wasmGC {
        optimization = probeOpt
        outOfProcess = true
        processMemory = 8192
        obfuscated = true
        sourceMap = false
        targetFileName = "rell-playground-bridge.wasm"
    }
}

// Mirror the generated JS into web/public so the SPA dev server / Vite build can serve it
// without dancing through bridge's build dir.
val copyTeavmToWeb by tasks.registering(Copy::class) {
    group = LifecycleBasePlugin.BUILD_GROUP
    description = "Copies the TeaVM-generated JS module into web/public for the SPA to serve."
    dependsOn(tasks.generateJavaScript)
    from(layout.buildDirectory.dir("generated/teavm/js"))
    into(rootProject.layout.projectDirectory.dir("web/public/teavm"))
}

tasks.build {
    dependsOn(copyTeavmToWeb)
}
